### ISSUE TITLE
Compute_stepsize function in proximal_grad

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-glm#17]
Currently the stepsize computation in `proximal_grad` is still embedded within the code, which makes it hard to manage it with Dask.  If the `proximal_grad` method is useful then it would be nice to pull this function out.

cc @moody-marlin

**Comment by moody-marlin** [comment]
So this is where the regularization stuff gets hairy; `proximal_grad` is an algorithm for regularized logistic problems, which means the function evaluations within `compute_stepsize` need to be a *modified* `loglike` function; this in turn makes jitting compute_stepsize more complicated because it now needs a function argument.

**Comment by mrocklin** [comment]
I'm not looking to jit, I'm looking to wrap with dask.delayed.  It is fine
to take a function as an input in this case.
